import {productImages} from '../utils/images'
const data = [
    {
        id:1,
        title:"SAE 10W30",
        category:"ENGINE OIL",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:21,
        img: productImages[0],
        },
        {
        id:2,
        title:"SAE 5W30",
        category:"ENGINE OIL",
        des:"High Quality Full Synthetic",
        quantity:1,
        price:25,
        img: productImages[1],
        },
        {
        id:3,
        title:"SAE 0W20",
        category:"ENGINE OIL",
        des:"High Quality Full Synthetic Blend",
        quantity:1,
        price:31,
        img: productImages[2],
        },
        {
        id:4,
        title:"SAE 0W30",
        category:"ENGINE OIL",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:12,
        img: productImages[3],
        },
        {
        id:5,
        title:"CVT FLUID",
        category:"AUTOMATIC TRANSMISSION FLUID",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:20,
        img: productImages[4],
        },
        {
        id:6,
        title:"ATF III H",
        category:"AUTOMATIC TRANSMISSION FLUID",
        des:"High Quality Mineral Blend",
        quantity:1,
        price:11,
        img: productImages[5],
        },
        {
        id:7,
        title:"ATF Steering Fluid",
        category:"UNIVERSAL POWER STREERING FLUID",
        des:"High Quality Mineral Blend",
        quantity:1,
        price:21,
        img: productImages[6],
        },
        {
        id:8,
        title:"EP 75W80",
        category:"GEAR & TRANSMISSION FLUID",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:31,
        img: productImages[7],
        },
        {
        id:9,
        title:"SAE 10W40",
        category:"ENGINE OIL",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:15,
        img: productImages[8],
        },
        {
        id:10,
        title:"SAE 5W40",
        category:"ENGINE OIL",
        des:"High Quality Full Synthetic Blend",
        quantity:1,
        price:25,
        img: productImages[9],
        },
        {
        id:11,
        title:"SAE 5W30",
        category:"ENGINE OIL",
        des:"High Quality Full Synthetic Blend",
        quantity:1,
        price:16,
        img: productImages[10],
        },
        {
        id:12,
        title:"SAE 0W30",
        category:"ENGINE OIL",
        des:"High Quality Full Synthetic Blend",
        quantity:1,
        price:19,
        img: productImages[11],
        },
        {
        id:13,
        title:"DSG Fluid",
        category:"AUTOMATIC TRANSMISSION FLUID",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:21,
        img: productImages[12],
        },
        {
        id:14,
        title:"ATF III",
        category:"AUTOMATIC TRANSMISSION FLUID",
        des:"High Quality Mineral Blend",
        quantity:1,
        price:65,
        img: productImages[13],
        },
        {
        id:15,
        title:"ATF II",
        category:"AUTOMATIC TRANSMISSION FLUID",
        des:"High Quality Mineral Blend",
        quantity:1,
        price:18,
        img: productImages[14],
        },
        {
        id:16,
        title:"EP 80W90",
        category:"GEAR & TRANSMISSION FLUID",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:21,
        img: productImages[15],
        },
        {
        id:17,
        title:"SAE 20W50",
        category:"ENGINE OIL",
        des:"High Quality Mineral Blend",
        quantity:1,
        price:45,
        img: productImages[16],
        },
        {
        id:18,
        title:"EP 10W40",
        category:"TURBO DIESEL ENGINE OI",
        des:"High Quality Synthetic Blend",
        quantity:1,
        price:16,
        img: productImages[17],
        },
]

export default data